"use client"
import '@/styles/globals.css'
import NavMember from '@components/NavMember'
import { Inter } from 'next/font/google'
import { ToastContainer } from 'react-toastify';
import { store } from '@redux/store';
import { Provider } from 'react-redux'
import { useEffect } from 'react';
import { cutLot } from './api/getAPI/sale';

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  useEffect(() => {
    const checkMidnight = async () => {
      const now = new Date();
      const hours = now.getHours();
      const minutes = now.getMinutes();
      //console.log(hours, minutes);
      if (hours === 0 && minutes === 0) {
        const res = await cutLot();
      }
    };

    // Check every second (10000 milliseconds)
    const intervalId = setInterval(checkMidnight, 10000);

    // Clean up the interval when the component is unmounted
    return () => {
      clearInterval(intervalId);
    };
  }, []);

  return (
    <html lang="en">
      <body>
        <Provider store={store}>
          <NavMember>
            {children}
          </NavMember>
          <ToastContainer position={'bottom-right'} icon={false}/>
        </Provider>
      </body>
    </html>
  )
}
